name: Java CI with Maven

on:
  push:
    branches: [ "prerelease"]
jobs:
  deploy-mvn-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          cache: maven
      - name: Create New Release
        run: mvn release:prepare -Darguments="-DskipTests -Dpmd.skip=true -Dspotbugs.skip=true" -B
      - name: Update snapshot version
        run: mvn release:perform -Darguments="-DskipTests -Dpmd.skip=true -Dspotbugs.skip=true"

#      - name: Deploy to Maven Central
#        run: mvn -B deploy --file pom.xml -Prelease -DskipTests
#        env:
#          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
#          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
